### ISSUE TITLE
Dot Executable: /usr/bin/dot  - File does not exist

### ISSUE THREAD

**Issue by igorrosenberg** [igorrosenberg/grails-plugin-uml-class-diagram#12]
When running the plugin for the first time:
```
Dot Executable: /usr/bin/dot
File does not exist
Cannot find Graphviz. You should try

@startuml
testdot
@enduml

or

java -jar plantuml.jar -testdot
```

**Comment by igorrosenberg** [comment]
The plugin depends on http://www.plantuml.com/ for the UML rendering. PlantUML is bundled within the plugin as a dependency. But PlantUML itself depends on GraphViz, as explained here:
http://www.plantuml.com/graphvizdot.html

So it is compulsory to install on the server the GraphViz software: 
http://www.graphviz.org/Download.php

**Comment by bengrandin-thetribe** [comment]
Hello,

I installed it following the link : http://www.graphviz.org/Download.php
 and its not working 

Thus, this link is dead http://www.plantuml.com/graphvizdot.html
